### ISSUE TITLE
[Editor] Create posts

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Nitro-Web#119]
```gherkin
Feature: Create a post
  As a user
  I would like to create a post
  To say something to everyone in the community
```

Hints: Consider to use [tiptap](https://github.com/scrumpy/tiptap) (vuejs wrapper for [prosemirror](https://prosemirror.net/)). Prosemirror is highly customizable and tiptap provides convenient features on top.

**Comment by roschaefer** [comment]
@appinteractive I updated your user story.

The edit shows the full power of user-stories and reflecting your requirements: The user does not want to use tiptap just because. She wants *to create posts*, she does not care what underlying JS library she's using. The JS library is a mere implementation detail. :wink: 

The user-stories save us from interesting libraries which provide no further value to the end user.
