### ISSUE TITLE
Transfer and sort out issues of the WebApp repo

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Nitro-Web#147]
**Describe the current situation**
Although the Alpha version is a dead development branch there are still many issues in its WebApp repo that apply to the Nitro version as well. It's also confusing to manage two repos.

**Expected situation**
Transfer all issues applying to Nitro to the Nitro-Web repo and close the rest.

**Comment by roschaefer** [comment]
@sushidave would it be OK to create an extra issue [here](https://github.com/Human-Connection/Human-Connection/issues) for every problem that exists in the alpha which also applies to the new codebase?

I'll close this for now, if you don't mind. This issue is very generic, so I don't know how to finish it.
